CREATE TABLE IF NOT EXISTS Status (
  title VARCHAR(256) UNIQUE PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(256),
  status VARCHAR(256),
  project_title VARCHAR(256),
  FOREIGN KEY (status)
    REFERENCES Status (title),
  FOREIGN KEY (project_title)
    REFERENCES Project (title)
);

CREATE TABLE IF NOT EXISTS Project (
  title VARCHAR(256) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Notes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT,
  project_title VARCHAR(256),
  FOREIGN KEY (project_title)
    REFERENCES Project (title)
);
