CREATE TABLE IF NOT EXISTS Status (
  title VARCHAR(256) UNIQUE PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(256),
  status VARCHAR(256),
  FOREIGN KEY (status)
    REFERENCES Status (title)
);
